### ISSUE TITLE
[Request] Rom settings

### ISSUE THREAD

**Issue by Zach1812** [spruceUI/spruceOS#196]
I am loving my Spruce. However when changing the rom settings (ie press X and select core/power/etc.) it’s quite annoying to have to select each one and then have to reload the settings to change it to something else. 

While I understand Spruce is quite optimized, there are still some settings I’d like to tweak, and having to hop in there twice to switch CPU mode to the one to the left is annoying. Is there a way this could be changed so I could select what I want from the options, then accept the results rather than having them automatically selected when I switch them.

**Comment by Sundownersport** [comment]
Thanks for the feedback, we went with this method in a effort to reduce the number of options in the X menu and haven't given it much thought since we changed it. We will look into whether this is possible withing the limitations of MainUI that we are under.

**Comment by ryanmsartor** [comment]
This would require a rework of the config files for each platform, as well as changes to the cpu mode scripts, and on top of that would add additional lines to the X button menu - which can only display 6 options at once before scrolling is required, which I'd really like to avoid.

What I'd recommend is using the per-game launch override options to save those CPU modes and core selections on a per-game basis so that you aren't forever toggling.
