### ISSUE TITLE
Plugging/unplugging power cable wakes the device

### ISSUE THREAD

**Issue by laesetuc** [spruceUI/spruceOS#245]
If the device is in suspend mode, plugging or unplugging the device wakes up the device.
In my opinion, the device should remain in the same state, and plugging/unplugging the power cable should not change the state of the device.  

Steps to reproduce:

1. Tap power button to suspend the device (screen is off)
2. Plug a power cable into the USB C port
3. Device wakes up (screen is on)
4. Tap power button to suspend the device again (screen is off)
5. Unplug the power cable from the USB C port
6. Device wakes up (screen is on)

My use case is that I charge the device overnight.  In the morning I pull the device off power and put it straight into my pocket. Doing so wakes the device up and drains the battery if I am not careful to check.

I have compared this behaviour with my Miyoo Mini running Onion OS and it handles the plugging/unplugging without the device changing state.

First world problems I know, but it is a nice to have.  Thank you!

**Comment by XanXic** [comment]
This is a hardware thing that's out of our control. Like this is present on stock if you take your spruce SD Card out. If the MM+ doesn't do it and the A30 does that's just because of the FW or hardware setup Miyoo did. Miyoo is incredibly unlikely to release a firmware that changes it. They seem done with the A30 now.

I'd recommend using spruce 3.1.0 features like 'shutdown in sleep', 'shutdown when idle', and auto shutdown/resume. The sleep function on the A30 is not super great at conserving battery being a linux device. The like 13 second boot time you may have to go through to get back into your game is certainly worth the battery life you'll save having the device completely shut off when you're not using it.
