### ISSUE TITLE
Corrupted game state file not handled gracefully

### ISSUE THREAD

**Issue by ngokevin** [spruceUI/spruceOS#258]
I ran into a corrupted game state file somehow (`.state` file). In the file explorer, I saw the file was 0KB.

If I tried to load from slot 1, it'd get an error. That's fine.

If I tried to **save** to slot 1 while there's a corrupted game state file, things break down:

- Notification stuck at "Saving game state (0%)"
- Can no longer load game states in other slots
- Exit game freezes the entire system

If a corrupted game state file is detected, either by file size check, error, or timeout, then it should be handled gracefully. Perhaps delete the existing state file if it's obviously corrupt?

**Comment by Sundownersport** [comment]
Which save was this? RA state in Saves/states or was it an in game menu save in the Roms folder?

when you deleted this corrupt file did the save/load work properly after?

**Comment by ngokevin** [comment]
I believe it was Saves/states, it was not the in game menu save. It was suffixed `.state`.

Once I deleted it, I can save/load to Slot 1 fine now, no issues.

**Comment by XanXic** [comment]
So we are unsure what a realistic solution is for this. We can't run a check over every save for 0kb ones since that'd be a rather intense process, and when should we do that? If we do a save check that adds to launch time. And then it's back to what should we do really? If we just deleted it and started you up we'd certainly have more people angry their saved suddenly got deleted rather than debugging a corrupted save experience.

I'm more surprised RetroArch doesn't handle that gracefully. But I don't think this is a common issue.

I experience this quite a bit personally just because of Syncthing and even for me, it'd cause a ton of chaos if Spruce did any handling of the save file. I wouldn't want that at all. Getting a notification of like "oh your save is corrupt" wouldn't tell _me_ anything I didn't know since I'm used to that issue.

I'm not against a corrupt save detector of some kind but at it's most it would just inform you and could not interact or fix it without causing more issues. Idk if any other OS has a similar feature or way to handle that scenario.

**Comment by ngokevin** [comment]
I deleted the file so I'm fine. Is there anything that could be done about Spruce crashing in case it fails or gets stuck saving over a bad file? There was another bit where it gets stuck say "Saving state to slot #1" and then trying to exit the game freezes the system. I'm okay to not fix unless it happens to me again.

**Comment by ngokevin** [comment]
My suggestion is have a 5-10 second timeout for saving the file, and if it's still hanging, display an error message "Failed to save to slot #1" and exit that command. Else can close this.
