### ISSUE TITLE
Suggestion - less restrictive subfolder pattern in /App/MiyooGamelist/generate.sh

### ISSUE THREAD

**Issue by Kickbut101** [spruceUI/spruceOS#262]
https://github.com/spruceUI/spruceOS/blob/3ec84cf6176a70efef8bc930e4b7cfc0ce7c73e7/App/MiyooGamelist/generate.sh#L40

Limiting this to just "Imgs" feels a bit restrictive for no reason. Especially when it just fails or exits with no output.

After using the Skraper app to get pictures it left behind the pictures in "Imgs" as intended in each Rom folder, but also the "media" folder.

I couldn't understand why the MiyooGamelist generator was failing to update/make the gamelist.xml until I saw this.

Suggest changing this regex pattern to "^Imgs$|^media$|^\." as that's a common use case for anyone *sprucing* ;) up their collection with metadata and pictures.

**Comment by Sundownersport** [comment]
Thank you for pointing this out!

we keep the boxart folder structure this way in order to keep it more user friendly for people using rom sets with included boxart for Onion and Garlic.

There should be an option to change this directly with Skraper so you don’t need to rename anything manually.

thanks!

**Comment by Kickbut101** [comment]
> Thank you for pointing this out!
> 
> we keep the boxart folder structure this way in order to keep it more user friendly for people using rom sets with included boxart for Onion and Garlic.
> 
> There should be an option to change this directly with Skraper so you don’t need to rename anything manually.
> 
> thanks!

Does additionally allowing for a "media" folder disqualify people from Onion and Garlic?

**Comment by XanXic** [comment]
Unsure what you mean by disqualify from Onion and Garlic?

We are open to it, it just will take testing it and all that to put it in mainline. Idk what the effects on gamelist it'll have in total. Sun was referring to in Skraper you can map the output whoever you need to. So if you're running Skraper on your romset you can have it automatically save to imgs instead of media. 

I believe Skraper by default uses media and puts them into subfolders like /boxart/ etc which might interfere with the gamelist generator. Sometimes it's better for us to make users bend to our will then try to reach out to everyone elses lol. Terrible metaphor but the reason we aren't just like "oh okay add media to the sub folder" we need to know if the media being in folders within the media folder is good to go or an issue? If it's an issue do we need to rewrite the whole app to handle it? Is it worth it? etc etc. I can't say right now having not looked at the code for gamelist. But suddenly we need to be sure Skraper works perfectly instead of sort of boxing users in to our method that currently works.

All that said if you want to shortcut the fix and bypass our internal queue you could put up a PR and let us know how it works. We are obviously open to new contributors. But I'm sure we'll look at it at some point, we want to offer ScreenScraper support natively and it might come up then.

Fwiw though MainUI (The stock we and things like Onion are built on) doesn't support metadata or screenshots. It's only boxarts.

**Comment by Kickbut101** [comment]
I'm aware, I was hedging (guessing) that the additional folder "media" was largely safe to add into the pattern. Again guessing that it wouldn't really affect gamelist.

I understand the caution, and yes Skraper does normally want to default to both an Img file and the media/mix folder.

**Comment by ryanmsartor** [comment]
MainUI can only see image files. If a user is not using a miyoogamelist.xml for a given system, then the emulator configs automatically point to the Imgs folder to look for images. If we enable additional media folders (whether they are called `media` or anything else, I just mean any other folders to search for media) then that increases the legwork we have to do while investigating user issues regarding artwork. I don't want to have to cater to two different classes of users. Everyone can use the Imgs folders that ship with spruce. There is really no reason to add support for other folders. XanXic has already described an easy workaround with Skraper to comply with the spruce standard.

**Comment by Kickbut101** [comment]
Understood, it wasn't a workflow I was attempting to have supported, it was simply excess folders that I was suggesting we ignore (vs having the script break/stop when it finds them). No worries.
